import { parseJsonMap, valueAsBoolean, valueAsString } from "./designCore.helpers.js";
import type { BrownfieldReadinessSummary, CurrentStateBoundarySummary, DiscoveredStateImportPlanSummary, NetworkObjectModel, V1DiscoveryAreaRow, V1DiscoveryCurrentStateControlSummary, V1DiscoveryFinding, V1DiscoveryImportTargetRow, V1DiscoveryReadiness, V1DiscoveryRequirementDriver, V1DiscoveryState, V1DiscoveryTask } from "../designCore.types.js";

export const V1_DISCOVERY_CURRENT_STATE_CONTRACT = "V1_DISCOVERY_CURRENT_STATE_CONTRACT" as const;
export const V1_MANUAL_DISCOVERY_BOUNDARY_ROLE = "MANUAL_DISCOVERY_BOUNDARY_NO_LIVE_DISCOVERY_CLAIMS" as const;

type DiscoverySite = { id: string; name: string; siteCode?: string | null; vlans?: unknown[] };
type DiscoveryProject = { discoveryJson?: string | null; requirementsJson?: string | null; environmentType?: string | null; sites?: DiscoverySite[]; brownfieldImports?: unknown[]; brownfieldNetworks?: unknown[]; dhcpScopes?: unknown[]; ipPools?: unknown[]; ipAllocations?: unknown[] };
type FieldDef = { key: string; label: string; aliases: string[]; requiredFor: string[] };
type TargetDef = { key: string; label: string; examples: string[]; requiredFor: string[]; keywords: RegExp; remediation: string };

const FIELDS: FieldDef[] = [
  { key: "topology", label: "Topology baseline", aliases: ["topologyText", "topologyBaseline", "topology"], requiredFor: ["brownfield", "migration", "multiSite", "cloudHybrid"] },
  { key: "inventory", label: "Inventory and lifecycle", aliases: ["inventoryText", "inventoryNotes", "inventory"], requiredFor: ["brownfield", "migration", "platformRefresh"] },
  { key: "addressing", label: "Addressing and VLAN baseline", aliases: ["addressingText", "addressingVlanBaseline", "addressing"], requiredFor: ["brownfield", "migration", "overlapReview"] },
  { key: "routing", label: "Routing and transport baseline", aliases: ["routingText", "routingTransportBaseline", "routing"], requiredFor: ["migration", "multiSite", "dualIsp", "cloudHybrid"] },
  { key: "security", label: "Security posture", aliases: ["securityText", "securityPosture", "security"], requiredFor: ["migration", "remoteAccess", "guestAccess", "managementAccess"] },
  { key: "wireless", label: "Wireless baseline", aliases: ["wirelessText", "wirelessBaseline", "wireless"], requiredFor: ["guestAccess", "wireless"] },
  { key: "gaps", label: "Gaps and pain points", aliases: ["gapText", "gapsPainPoints", "gaps", "painPoints"], requiredFor: ["brownfield", "migration"] },
  { key: "constraints", label: "Constraints and dependencies", aliases: ["constraintsText", "constraintsDependencies", "constraints"], requiredFor: ["migration", "multiSite", "dualIsp"] },
  { key: "notes", label: "Additional notes", aliases: ["notesText", "extraNotes", "notes"], requiredFor: ["review"] },
];

const TARGETS: TargetDef[] = [
  { key: "subnet-ipam", label: "Subnet/IPAM exports", examples: ["IPAM CSV", "NetBox prefix export", "spreadsheet subnet register"], requiredFor: ["brownfield", "migration", "overlapReview"], keywords: /\b(ipam|subnet export|prefix export|netbox|infoblox|bluecat|subnet register)\b/i, remediation: "Import or paste the current subnet and prefix register before claiming brownfield overlap readiness." },
  { key: "dhcp-scopes", label: "DHCP scope exports", examples: ["Windows DHCP export", "firewall DHCP export"], requiredFor: ["migration", "guestAccess", "voice", "wireless"], keywords: /\b(dhcp|scope|lease|reservation)\b/i, remediation: "Capture DHCP scopes, exclusions, leases, and reservations before migration cutover planning." },
  { key: "arp-tables", label: "ARP tables", examples: ["router show arp", "firewall ARP table"], requiredFor: ["brownfield", "migration"], keywords: /\b(arp|show arp|ip arp)\b/i, remediation: "Capture ARP evidence when endpoint placement or duplicate gateway risk matters." },
  { key: "mac-tables", label: "MAC tables", examples: ["switch MAC address table", "controller client table"], requiredFor: ["brownfield", "migration", "wireless"], keywords: /\b(mac address-table|mac table|cam table|client table)\b/i, remediation: "Capture switch MAC or client-table evidence before physical move or segmentation migration claims." },
  { key: "routing-tables", label: "Routing tables", examples: ["show ip route", "BGP routes", "OSPF database"], requiredFor: ["multiSite", "dualIsp", "cloudHybrid", "migration"], keywords: /\b(show ip route|routing table|ospf|bgp|eigrp|static route|default route|route table|redistribution)\b/i, remediation: "Capture routing table/control-plane evidence before route-domain or failover readiness is trusted." },
  { key: "firewall-configs", label: "Firewall configs and policy exports", examples: ["Palo Alto config export", "FortiGate config", "zone matrix"], requiredFor: ["guestAccess", "remoteAccess", "cloudHybrid", "migration"], keywords: /\b(firewall|policy export|security rule|nat rule|palo alto|fortigate|asa|zone|vpn)\b/i, remediation: "Capture firewall zones, NAT, remote-access, and policy exports before security-flow migration is trusted." },
  { key: "switch-configs", label: "Switch configs", examples: ["running-config", "interface status", "VLAN database"], requiredFor: ["brownfield", "migration", "voice", "managementAccess"], keywords: /\b(running-config|switch config|interface status|trunk|access vlan|voice vlan|show vlan)\b/i, remediation: "Capture current VLAN/trunk/interface evidence before access-layer migration planning." },
  { key: "lldp-cdp", label: "LLDP/CDP neighbor data", examples: ["show cdp neighbors", "show lldp neighbors"], requiredFor: ["multiSite", "migration", "platformRefresh"], keywords: /\b(lldp|cdp|neighbor|topology export)\b/i, remediation: "Capture neighbor data to prevent guessed physical topology and uplink mapping." },
  { key: "cloud-network", label: "Cloud VPC/VNet data", examples: ["AWS VPC route tables", "Azure VNet/subnet export", "GCP VPC export"], requiredFor: ["cloudHybrid", "migration"], keywords: /\b(vpc|vnet|aws|azure|gcp|cloud route|route table|expressroute|direct connect|vpn gateway)\b/i, remediation: "Capture cloud network, route table, and gateway evidence before hybrid-route readiness is claimed." },
  { key: "inventory-cmdb", label: "NetBox-style inventory / CMDB", examples: ["NetBox device export", "CMDB inventory", "NMS inventory"], requiredFor: ["brownfield", "platformRefresh"], keywords: /\b(netbox|cmdb|nms inventory|device export|asset inventory|serial|eos|eol)\b/i, remediation: "Capture inventory/CMDB evidence before lifecycle, refresh, and reuse assumptions are trusted." },
];

function lines(text: string): string[] { return text.split(/\r?\n/).map((line) => line.replace(/^[-*•\s]+/, "").trim()).filter(Boolean); }
function value(map: Record<string, unknown>, aliases: string[]): string { for (const alias of aliases) { const next = valueAsString(map[alias]); if (next) return next; } return ""; }
function hasImport(map: Record<string, unknown>, key: string): boolean { const item = map[key] ?? map[`${key}Import`] ?? map[`${key}Json`] ?? map[`${key}Text`]; if (Array.isArray(item)) return item.length > 0; if (item && typeof item === "object") return Object.keys(item).length > 0; return valueAsString(item).length > 0; }
function num(raw: unknown, fallback = 0): number { const parsed = typeof raw === "number" ? raw : Number(raw); return Number.isFinite(parsed) ? parsed : fallback; }
function bool(map: Record<string, unknown>, ...keys: string[]): boolean { return keys.some((key) => valueAsBoolean(map[key]) || /\b(yes|true|required|enabled|migration|brownfield|upgrade|refresh|multi-site|multisite|hybrid)\b/i.test(valueAsString(map[key]))); }
function conflict(text: string): boolean { return /\b(conflict|duplicate|overlap|mismatch|stale|unsupported|legacy|eol|eos)\b/i.test(text); }
function source(state: V1DiscoveryState): string { return state === "NOT_PROVIDED" ? "not provided" : state === "MANUALLY_ENTERED" ? "manual entry" : state === "IMPORTED" ? "imported artifact" : state === "VALIDATED" ? "validated import" : state === "CONFLICTING" ? "conflicting evidence" : "review required"; }
function readiness(state: V1DiscoveryState, required: boolean): V1DiscoveryReadiness { if (state === "CONFLICTING") return "BLOCKED"; if (required && (state === "NOT_PROVIDED" || state === "REVIEW_REQUIRED")) return "REVIEW_REQUIRED"; if (state === "VALIDATED") return "READY"; if (state === "IMPORTED" || state === "MANUALLY_ENTERED" || state === "REVIEW_REQUIRED") return "REVIEW_REQUIRED"; return "NOT_READY"; }
function worst(values: V1DiscoveryReadiness[]): V1DiscoveryReadiness { if (values.includes("BLOCKED")) return "BLOCKED"; if (values.includes("REVIEW_REQUIRED")) return "REVIEW_REQUIRED"; if (values.includes("NOT_READY")) return "NOT_READY"; return "READY"; }
function findingReady(severity: V1DiscoveryFinding["severity"]): V1DiscoveryReadiness { return severity === "BLOCKING" ? "BLOCKED" : severity === "REVIEW_REQUIRED" || severity === "WARNING" ? "REVIEW_REQUIRED" : severity === "INFO" ? "NOT_READY" : "READY"; }
function area(input: Omit<V1DiscoveryAreaRow, "contract">): V1DiscoveryAreaRow { return { contract: V1_DISCOVERY_CURRENT_STATE_CONTRACT, ...input }; }
function target(input: Omit<V1DiscoveryImportTargetRow, "contract">): V1DiscoveryImportTargetRow { return { contract: V1_DISCOVERY_CURRENT_STATE_CONTRACT, ...input }; }
function task(input: Omit<V1DiscoveryTask, "contract">): V1DiscoveryTask { return { contract: V1_DISCOVERY_CURRENT_STATE_CONTRACT, ...input }; }
function driver(input: Omit<V1DiscoveryRequirementDriver, "contract">): V1DiscoveryRequirementDriver { return { contract: V1_DISCOVERY_CURRENT_STATE_CONTRACT, ...input }; }
function pushFinding(findings: V1DiscoveryFinding[], finding: V1DiscoveryFinding): void { if (!findings.some((item) => item.code === finding.code)) findings.push(finding); }

export function buildV1DiscoveryCurrentStateControl(params: { project: DiscoveryProject; networkObjectModel: NetworkObjectModel; currentStateBoundary: CurrentStateBoundarySummary; brownfieldReadiness: BrownfieldReadinessSummary; discoveredStateImportPlan: DiscoveredStateImportPlanSummary; }): V1DiscoveryCurrentStateControlSummary {
  const { project, networkObjectModel, currentStateBoundary, brownfieldReadiness, discoveredStateImportPlan } = params;
  const discovery = parseJsonMap(project.discoveryJson); const requirements = parseJsonMap(project.requirementsJson);
  const combinedText = FIELDS.map((field) => value(discovery, field.aliases)).join("\n");
  const siteCount = Math.max(project.sites?.length ?? 0, num(requirements.siteCount), num(requirements.sites));
  const context = `${valueAsString(requirements.planningFor)} ${valueAsString(requirements.projectStage)} ${valueAsString(requirements.primaryGoal)} ${valueAsString(project.environmentType)} ${combinedText}`;
  const signals: Record<string, boolean> = {
    brownfield: bool(requirements, "brownfield", "existingNetwork", "currentState") || /\b(brownfield|existing network|current state|as-is)\b/i.test(context),
    migration: bool(requirements, "migration", "migrate", "upgrade", "refresh") || /\b(migration|migrate|upgrade|refresh|cutover)\b/i.test(context),
    multiSite: siteCount > 1 || bool(requirements, "multiSite", "wan", "interSiteTrafficModel"),
    dualIsp: bool(requirements, "dualIsp", "dualISP", "redundantInternet"), cloudHybrid: bool(requirements, "cloudHybrid", "cloudConnected", "hybridCloud"), guestAccess: bool(requirements, "guestAccess", "guestWifi", "guestWiFi"), remoteAccess: bool(requirements, "remoteAccess", "vpn"), managementAccess: bool(requirements, "management", "managementAccess", "adminAccess"), voice: bool(requirements, "voice", "voiceVlan", "phones"), wireless: bool(requirements, "wireless", "guestWifi", "guestWiFi"), platformRefresh: /\b(refresh|eol|eos|legacy|replace)\b/i.test(context), overlapReview: /\b(overlap|duplicate subnet|duplicate vlan|conflict)\b/i.test(context), review: true,
  };
  const areaRows = FIELDS.map((field) => { const text = value(discovery, field.aliases); const requiredFor = field.requiredFor.filter((key) => signals[key]); const validated = valueAsBoolean(discovery[`${field.key}Validated`]); const imported = hasImport(discovery, `${field.key}Import`) || (hasImport(discovery, field.key) && /\b(import|csv|json|export|netbox|config)\b/i.test(text)); const state: V1DiscoveryState = conflict(text) ? "CONFLICTING" : validated && text ? "VALIDATED" : imported && text ? "IMPORTED" : text ? "MANUALLY_ENTERED" : requiredFor.length ? "REVIEW_REQUIRED" : "NOT_PROVIDED"; return area({ areaKey: field.key, area: field.label, state, sourceType: source(state), requiredFor, evidenceCount: lines(text).length, sourceRequirementIds: requiredFor.map((key) => `requirements:${key}`), sourceObjectIds: [], readinessImpact: readiness(state, requiredFor.length > 0), reviewReason: state === "CONFLICTING" ? "Captured current-state evidence contains conflict/risk language and must be reconciled before authority is lifted." : state === "NOT_PROVIDED" || state === "REVIEW_REQUIRED" ? `Discovery area required for ${requiredFor.join(", ") || "future review"}, but evidence is not validated.` : "Manual or imported evidence is captured but still needs engineer validation before it becomes authoritative.", notes: text ? lines(text).slice(0, 3) : [`No ${field.label.toLowerCase()} captured yet.`] }); });
  const importTargets = TARGETS.map((def) => { const requiredFor = def.requiredFor.filter((key) => signals[key]); const mentioned = def.keywords.test(combinedText) || hasImport(discovery, def.key); const imported = hasImport(discovery, def.key) || (mentioned && /\b(import|export|csv|json|config|show )\b/i.test(combinedText)); const validated = valueAsBoolean(discovery[`${def.key}Validated`]); const state: V1DiscoveryState = mentioned && /\b(overlap|duplicate|conflict|mismatch)\b/i.test(combinedText) ? "CONFLICTING" : validated && imported ? "VALIDATED" : imported ? "IMPORTED" : mentioned ? "MANUALLY_ENTERED" : requiredFor.length ? "REVIEW_REQUIRED" : "NOT_PROVIDED"; return target({ targetKey: def.key, target: def.label, state, sourceExamples: def.examples, requiredFor, sourceRequirementIds: requiredFor.map((key) => `requirements:${key}`), readinessImpact: readiness(state, requiredFor.length > 0), reconciliationNeed: state === "VALIDATED" ? "Validated import can feed future reconciliation." : def.remediation, notes: [state === "NOT_PROVIDED" ? "No matching source evidence detected." : `${def.label} evidence appears in discovery/current-state notes.`] }); });
  const tasks: V1DiscoveryTask[] = [];
  const addTask = (key: string, title: string, detail: string, keys: string[], priority: "HIGH" | "MEDIUM" | "LOW") => { const linkedTargets = importTargets.filter((item) => keys.includes(item.targetKey)).map((item) => item.target); const blockers = importTargets.filter((item) => keys.includes(item.targetKey) && ["NOT_PROVIDED", "REVIEW_REQUIRED", "CONFLICTING"].includes(item.state)).map((item) => item.target); tasks.push(task({ taskId: `V1:${key}:${tasks.length + 1}`, requirementId: `requirements:${key}`, title, detail, linkedTargets, priority, state: blockers.length ? "OPEN" : "REVIEW_READY", readinessImpact: blockers.length ? "REVIEW_REQUIRED" : "READY", blockers })); };
  if (signals.brownfield) addTask("brownfield", "Current-state import required", "Brownfield work cannot be trusted from target-state requirements only.", ["subnet-ipam", "inventory-cmdb", "routing-tables", "firewall-configs", "lldp-cdp"], "HIGH");
  if (signals.migration) addTask("migration", "Migration comparison required", "Migration planning requires current-versus-target comparison for IPAM, DHCP, routing, firewall, switch, and cutover constraints.", ["subnet-ipam", "dhcp-scopes", "routing-tables", "firewall-configs", "switch-configs"], "HIGH");
  if (signals.multiSite) addTask("multiSite", "WAN/routing discovery required", "Multi-site designs need WAN edge, routing table, provider handoff, and neighbor evidence.", ["routing-tables", "lldp-cdp", "cloud-network"], "HIGH");
  if (signals.dualIsp) addTask("dualIsp", "Dual-ISP failover evidence required", "Dual ISP creates failover review, not fake circuits.", ["routing-tables", "firewall-configs"], "HIGH");
  if (signals.cloudHybrid) addTask("cloudHybrid", "Cloud network import/review required", "Hybrid cloud intent needs VPC/VNet, route table, gateway, firewall/NAT, and boundary evidence.", ["cloud-network", "routing-tables", "firewall-configs"], "HIGH");
  if (signals.guestAccess) addTask("guestAccess", "Guest isolation discovery required", "Guest access requires current SSID, VLAN, DHCP, firewall policy, and isolation evidence.", ["dhcp-scopes", "firewall-configs"], "MEDIUM");
  if (signals.remoteAccess) addTask("remoteAccess", "Remote-access control discovery required", "Remote access requires VPN, identity, logging, firewall, and route evidence.", ["firewall-configs", "routing-tables"], "MEDIUM");
  const requirementDrivers = Object.entries(signals).filter(([, active]) => active).map(([key]) => driver({ requirementId: `requirements:${key}`, value: "active/current-state relevant", affectedAreas: areaRows.filter((item) => item.requiredFor.includes(key)).map((item) => item.area), affectedImportTargets: importTargets.filter((item) => item.requiredFor.includes(key)).map((item) => item.target), generatedTaskIds: tasks.filter((item) => item.requirementId === `requirements:${key}`).map((item) => item.taskId), evidence: `V1 mapped ${key} to discovery areas/import targets instead of inventing current-state authority.`, readinessImpact: tasks.some((item) => item.requirementId === `requirements:${key}` && item.readinessImpact !== "READY") ? "REVIEW_REQUIRED" : "READY" }));
  const findings: V1DiscoveryFinding[] = []; const missingAreas = areaRows.filter((item) => item.requiredFor.length && ["NOT_PROVIDED", "REVIEW_REQUIRED"].includes(item.state)); const missingTargets = importTargets.filter((item) => item.requiredFor.length && ["NOT_PROVIDED", "REVIEW_REQUIRED"].includes(item.state)); const conflicts = [...areaRows.filter((item) => item.state === "CONFLICTING").map((item) => item.area), ...importTargets.filter((item) => item.state === "CONFLICTING").map((item) => item.target)];
  if (missingAreas.length) pushFinding(findings, { severity: "REVIEW_REQUIRED", code: "V1_REQUIRED_DISCOVERY_AREA_MISSING", title: "Required discovery areas are missing or unvalidated", detail: `${missingAreas.length} discovery area(s) are required but lack validated evidence.`, affectedAreas: missingAreas.map((item) => item.area), affectedImportTargets: [], readinessImpact: "REVIEW_REQUIRED", remediation: "Capture or import the missing current-state evidence, then mark it validated only after engineer review." });
  if (missingTargets.length) pushFinding(findings, { severity: "REVIEW_REQUIRED", code: "V1_IMPORT_TARGETS_NOT_READY", title: "Import/reconciliation targets are not ready", detail: `${missingTargets.length} structured import target(s) are required but not imported/validated.`, affectedAreas: [], affectedImportTargets: missingTargets.map((item) => item.target), readinessImpact: "REVIEW_REQUIRED", remediation: "Gather subnet/IPAM, DHCP, routing, firewall, switch, neighbor, cloud, or inventory evidence as applicable." });
  if (conflicts.length) pushFinding(findings, { severity: "BLOCKING", code: "V1_DISCOVERY_CONFLICT_REQUIRES_RECONCILIATION", title: "Discovery evidence contains conflict signals", detail: "Current-state notes include overlap, duplicate, conflict, mismatch, or stale-evidence language. The app must not promote this into authoritative design truth yet.", affectedAreas: areaRows.filter((item) => item.state === "CONFLICTING").map((item) => item.area), affectedImportTargets: importTargets.filter((item) => item.state === "CONFLICTING").map((item) => item.target), readinessImpact: "BLOCKED", remediation: "Reconcile conflicting evidence against durable IPAM/current-state imports before using it for implementation readiness." });
  const persistedBrownfield = (project.brownfieldImports?.length ?? 0) + (project.brownfieldNetworks?.length ?? 0); if (persistedBrownfield === 0) pushFinding(findings, { severity: "INFO", code: "V1_NO_ACTUAL_LIVE_DISCOVERY_IMPORT", title: "No live/imported current-state objects are persisted", detail: "Discovery remains a manual planning boundary. That is acceptable, but it is not live mapping or automatic discovery.", affectedAreas: ["Discovery/current-state"], affectedImportTargets: importTargets.filter((item) => item.requiredFor.length).map((item) => item.target), readinessImpact: "NOT_READY", remediation: "Keep claims labelled manual until importer/parser workflows populate durable current-state objects." });
  if (!combinedText.trim()) pushFinding(findings, { severity: "INFO", code: "V1_MANUAL_DISCOVERY_EMPTY_STATE", title: "Discovery workspace is empty", detail: "No current-state notes or import evidence were found. This is honest, but migration/current-state readiness must stay low.", affectedAreas: ["Discovery/current-state"], affectedImportTargets: [], readinessImpact: "NOT_READY", remediation: "Capture topology, inventory, addressing, routing, security, wireless, gaps, and constraints." });
  const stateCounts: Record<V1DiscoveryState, number> = { NOT_PROVIDED: 0, MANUALLY_ENTERED: 0, IMPORTED: 0, VALIDATED: 0, CONFLICTING: 0, REVIEW_REQUIRED: 0 }; for (const item of [...areaRows, ...importTargets]) stateCounts[item.state] += 1;
  const readinessValues = [...areaRows.map((item) => item.readinessImpact), ...importTargets.map((item) => item.readinessImpact), ...findings.map((item) => findingReady(item.severity))];
  const manuallyEnteredEvidenceCount = areaRows.filter((item) => item.state === "MANUALLY_ENTERED").length + importTargets.filter((item) => item.state === "MANUALLY_ENTERED").length; const importedEvidenceCount = areaRows.filter((item) => item.state === "IMPORTED").length + importTargets.filter((item) => item.state === "IMPORTED").length + persistedBrownfield; const validatedEvidenceCount = areaRows.filter((item) => item.state === "VALIDATED").length + importTargets.filter((item) => item.state === "VALIDATED").length; const reviewRequiredCount = areaRows.filter((item) => item.readinessImpact === "REVIEW_REQUIRED").length + importTargets.filter((item) => item.readinessImpact === "REVIEW_REQUIRED").length + findings.filter((item) => item.severity === "REVIEW_REQUIRED").length;
  return { contract: V1_DISCOVERY_CURRENT_STATE_CONTRACT, role: V1_MANUAL_DISCOVERY_BOUNDARY_ROLE, sourceOfTruthLevel: "manual-discovery-boundary", currentStateAuthority: "MANUAL_OR_IMPORTED_EVIDENCE_ONLY_NOT_LIVE_DISCOVERY", overallReadiness: worst(readinessValues.length ? readinessValues : ["NOT_READY"]), brownfieldMode: brownfieldReadiness.mode, importReadiness: discoveredStateImportPlan.readiness, siteCount, savedSiteCount: project.sites?.length ?? 0, modeledDeviceCount: networkObjectModel.summary.deviceCount, modeledInterfaceCount: networkObjectModel.summary.interfaceCount, configuredObjectCount: currentStateBoundary.configuredObjectCount, discoveredObjectCount: currentStateBoundary.discoveredObjectCount + persistedBrownfield, persistedIpamObjectCount: (project.ipPools?.length ?? 0) + (project.ipAllocations?.length ?? 0) + (project.dhcpScopes?.length ?? 0), areaRowCount: areaRows.length, importTargetCount: importTargets.length, taskCount: tasks.length, openTaskCount: tasks.filter((item) => item.state === "OPEN").length, requirementDriverCount: requirementDrivers.length, manuallyEnteredEvidenceCount, importedEvidenceCount, validatedEvidenceCount, conflictingEvidenceCount: stateCounts.CONFLICTING, reviewRequiredCount, stateCounts, areaRows, importTargets, tasks, requirementDrivers, findings, proofBoundary: ["V1 does not perform live network discovery, SNMP polling, config scraping, cloud API inventory, or automatic reconciliation.", "Manual notes can inform review tasks but cannot become authoritative discovered objects without explicit imported/validated evidence.", "Structured import targets are planning gates for future parsers; missing data stays review-required, not hidden behind confident summaries.", "Conflicting current-state evidence blocks discovery authority until reconciled with durable IPAM/current-state objects."], notes: ["Discovery/current-state has been promoted into backend design-core evidence without pretending it is live discovery.", `Brownfield mode ${brownfieldReadiness.mode}; evidence ${brownfieldReadiness.currentStateEvidence}; import readiness ${discoveredStateImportPlan.readiness}.`, `State coverage: validated=${validatedEvidenceCount}, imported=${importedEvidenceCount}, manual=${manuallyEnteredEvidenceCount}, conflict=${stateCounts.CONFLICTING}, review=${reviewRequiredCount}.`] };
}
