export type RequirementImpactLevel = "direct" | "indirect" | "evidence";

export type RequirementImpactRegistryItem = {
  key: string;
  label: string;
  category: string;
  impact: RequirementImpactLevel;
  outputAreas: string[];
  materializationTargets: string[];
  designConsequence: string;
  validationConsequence: string;
  diagramConsequence: string;
  reportConsequence: string;
};

export type RequirementImpactInventoryRow = RequirementImpactRegistryItem & {
  sourceValue: string;
  captured: boolean;
};

export const REQUIREMENT_IMPACT_REGISTRY: RequirementImpactRegistryItem[] = [
  {
    key: "planningFor",
    label: "Planning objective",
    category: "core",
    impact: "direct",
    outputAreas: ["project scenario", "topology pattern", "report narrative"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Controls the baseline scenario label and architecture pattern used by topology/report sections.",
    validationConsequence: "Design-core traceability must show whether planning objective is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose planning objective through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of planning objective so the requirement is not dead form data.",
  },
  {
    key: "projectPhase",
    label: "Project phase",
    category: "core",
    impact: "direct",
    outputAreas: ["greenfield/brownfield posture", "implementation review", "change planning"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Distinguishes clean builds from upgrades so implementation and brownfield risk are not treated the same.",
    validationConsequence: "Design-core traceability must show whether project phase is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose project phase through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of project phase so the requirement is not dead form data.",
  },
  {
    key: "environmentType",
    label: "Environment type",
    category: "core",
    impact: "direct",
    outputAreas: ["cloud/hybrid trigger", "edge topology", "service placement"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Triggers on-prem, cloud, or hybrid consequences in site, WAN, and service models.",
    validationConsequence: "Design-core traceability must show whether environment type is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose environment type through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of environment type so the requirement is not dead form data.",
  },
  {
    key: "complianceProfile",
    label: "Compliance / policy context",
    category: "core",
    impact: "indirect",
    outputAreas: ["security strictness", "logging expectations", "review findings"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Raises expected control strictness and report evidence requirements.",
    validationConsequence: "Design-core traceability must show whether compliance / policy context is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose compliance / policy context through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of compliance / policy context so the requirement is not dead form data.",
  },
  {
    key: "siteCount",
    label: "Site count",
    category: "core",
    impact: "direct",
    outputAreas: ["site records", "site block allocation", "WAN posture"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Creates or refreshes site rows and determines whether multi-site WAN planning is mandatory.",
    validationConsequence: "Design-core traceability must show whether site count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose site count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of site count so the requirement is not dead form data.",
  },
  {
    key: "usersPerSite",
    label: "Users per site",
    category: "core",
    impact: "direct",
    outputAreas: ["host demand", "subnet sizing", "access capacity"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Drives user VLAN host demand and capacity sizing.",
    validationConsequence: "Design-core traceability must show whether users per site is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose users per site through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of users per site so the requirement is not dead form data.",
  },
  {
    key: "internetModel",
    label: "Internet breakout model",
    category: "core",
    impact: "direct",
    outputAreas: ["WAN edge", "firewall placement", "transit design"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Changes whether internet is local, centralized, or WAN/cloud dependent.",
    validationConsequence: "Design-core traceability must show whether internet breakout model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose internet breakout model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of internet breakout model so the requirement is not dead form data.",
  },
  {
    key: "serverPlacement",
    label: "Server placement",
    category: "core",
    impact: "direct",
    outputAreas: ["services segment", "service centralization", "WAN dependency"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Creates/strengthens services placement and centralization assumptions.",
    validationConsequence: "Design-core traceability must show whether server placement is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose server placement through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of server placement so the requirement is not dead form data.",
  },
  {
    key: "primaryGoal",
    label: "Primary goal",
    category: "core",
    impact: "direct",
    outputAreas: ["validation emphasis", "security posture", "design tradeoffs"],
    materializationTargets: ["Project summary", "Site/topology intent", "Design-core traceability"],
    designConsequence: "Controls whether the plan prioritizes segmentation, cost, performance, availability, or simplicity.",
    validationConsequence: "Design-core traceability must show whether primary goal is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose primary goal through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of primary goal so the requirement is not dead form data.",
  },
  {
    key: "guestWifi",
    label: "Guest Wi-Fi required",
    category: "security",
    impact: "direct",
    outputAreas: ["guest VLAN", "guest zone", "internet-only policy"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Creates/strengthens isolated guest access expectations.",
    validationConsequence: "Design-core traceability must show whether guest wi-fi required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose guest wi-fi required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of guest wi-fi required so the requirement is not dead form data.",
  },
  {
    key: "voice",
    label: "Voice required",
    category: "edge",
    impact: "direct",
    outputAreas: ["voice VLAN", "QoS intent", "access edge"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Creates/strengthens voice segment and QoS expectations.",
    validationConsequence: "Design-core traceability must show whether voice required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose voice required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of voice required so the requirement is not dead form data.",
  },
  {
    key: "management",
    label: "Management network required",
    category: "security",
    impact: "direct",
    outputAreas: ["management VLAN", "management zone", "admin access control"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Creates/strengthens management plane isolation.",
    validationConsequence: "Design-core traceability must show whether management network required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose management network required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of management network required so the requirement is not dead form data.",
  },
  {
    key: "printers",
    label: "Printers required",
    category: "edge",
    impact: "direct",
    outputAreas: ["printer VLAN", "shared device policy", "access control"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Creates/strengthens printer/shared-device segmentation.",
    validationConsequence: "Design-core traceability must show whether printers required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose printers required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of printers required so the requirement is not dead form data.",
  },
  {
    key: "iot",
    label: "IoT required",
    category: "security",
    impact: "direct",
    outputAreas: ["IoT VLAN", "restricted zone", "specialty-device policy"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Creates/strengthens IoT/specialty-device isolation.",
    validationConsequence: "Design-core traceability must show whether iot required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose iot required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of iot required so the requirement is not dead form data.",
  },
  {
    key: "cameras",
    label: "Camera/security devices required",
    category: "security",
    impact: "direct",
    outputAreas: ["camera VLAN", "physical-security zone", "NVR/service policy"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Creates/strengthens camera/security-device isolation.",
    validationConsequence: "Design-core traceability must show whether camera/security devices required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose camera/security devices required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of camera/security devices required so the requirement is not dead form data.",
  },
  {
    key: "wireless",
    label: "Wireless required",
    category: "edge",
    impact: "direct",
    outputAreas: ["staff Wi-Fi VLAN", "AP placement", "SSID mapping"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Creates/strengthens staff wireless planning and AP capacity.",
    validationConsequence: "Design-core traceability must show whether wireless required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose wireless required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of wireless required so the requirement is not dead form data.",
  },
  {
    key: "remoteAccess",
    label: "Remote access required",
    category: "security",
    impact: "direct",
    outputAreas: ["remote-access segment", "VPN edge", "identity boundary"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Creates/strengthens VPN/remote-access policy and edge placement.",
    validationConsequence: "Design-core traceability must show whether remote access required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose remote access required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of remote access required so the requirement is not dead form data.",
  },
  {
    key: "dualIsp",
    label: "Dual ISP required",
    category: "resilience",
    impact: "direct",
    outputAreas: ["WAN transit", "edge redundancy", "failover review"],
    materializationTargets: ["Redundancy review", "WAN/edge posture", "Implementation risk"],
    designConsequence: "Triggers redundancy review and WAN/transit expectations.",
    validationConsequence: "Design-core traceability must show whether dual isp required is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose dual isp required through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of dual isp required so the requirement is not dead form data.",
  },
  {
    key: "cloudConnected",
    label: "Cloud connected",
    category: "cloud",
    impact: "direct",
    outputAreas: ["cloud edge", "hybrid routing", "cloud boundary"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Creates/strengthens cloud-edge and hybrid boundary planning.",
    validationConsequence: "Design-core traceability must show whether cloud connected is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud connected through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud connected so the requirement is not dead form data.",
  },
  {
    key: "guestPolicy",
    label: "Guest policy",
    category: "security",
    impact: "direct",
    outputAreas: ["guest policy matrix", "blocked internal flows", "NAT expectations"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Determines guest containment and internet-only behavior.",
    validationConsequence: "Design-core traceability must show whether guest policy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose guest policy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of guest policy so the requirement is not dead form data.",
  },
  {
    key: "voiceQos",
    label: "Voice QoS model",
    category: "edge",
    impact: "direct",
    outputAreas: ["QoS plan", "voice validation", "access prioritization"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Defines voice treatment and prioritization expectations.",
    validationConsequence: "Design-core traceability must show whether voice qos model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose voice qos model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of voice qos model so the requirement is not dead form data.",
  },
  {
    key: "managementAccess",
    label: "Management access model",
    category: "security",
    impact: "direct",
    outputAreas: ["admin-source restrictions", "management flows", "validation blockers"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Determines who can reach infrastructure management.",
    validationConsequence: "Design-core traceability must show whether management access model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose management access model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of management access model so the requirement is not dead form data.",
  },
  {
    key: "wirelessModel",
    label: "Wireless / SSID model",
    category: "edge",
    impact: "direct",
    outputAreas: ["SSID-to-VLAN mapping", "AP edge", "guest/staff split"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Determines staff, guest, and specialty SSID mapping.",
    validationConsequence: "Design-core traceability must show whether wireless / ssid model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose wireless / ssid model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of wireless / ssid model so the requirement is not dead form data.",
  },
  {
    key: "remoteAccessMethod",
    label: "Remote access method",
    category: "security",
    impact: "direct",
    outputAreas: ["VPN edge type", "identity controls", "remote flows"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Determines remote-access gateway and identity-control assumptions.",
    validationConsequence: "Design-core traceability must show whether remote access method is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose remote access method through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of remote access method so the requirement is not dead form data.",
  },
  {
    key: "cloudProvider",
    label: "Cloud provider",
    category: "cloud",
    impact: "indirect",
    outputAreas: ["cloud edge label", "provider handoff", "report assumptions"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Labels cloud target and provider-specific review context.",
    validationConsequence: "Design-core traceability must show whether cloud provider is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud provider through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud provider so the requirement is not dead form data.",
  },
  {
    key: "cloudConnectivity",
    label: "Cloud connectivity",
    category: "cloud",
    impact: "direct",
    outputAreas: ["site-to-cloud link", "cloud transit", "routing review"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines VPN/direct/SD-WAN/internet-only hybrid edge behavior.",
    validationConsequence: "Design-core traceability must show whether cloud connectivity is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud connectivity through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud connectivity so the requirement is not dead form data.",
  },
  {
    key: "resilienceTarget",
    label: "Resilience target",
    category: "resilience",
    impact: "direct",
    outputAreas: ["HA posture", "dual ISP review", "edge redundancy"],
    materializationTargets: ["Redundancy review", "WAN/edge posture", "Implementation risk"],
    designConsequence: "Determines single-path vs failover/HA expectations.",
    validationConsequence: "Design-core traceability must show whether resilience target is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose resilience target through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of resilience target so the requirement is not dead form data.",
  },
  {
    key: "securityPosture",
    label: "Security posture",
    category: "security",
    impact: "direct",
    outputAreas: ["zone strictness", "policy matrix", "validation severity"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Controls expected segmentation/control strictness.",
    validationConsequence: "Design-core traceability must show whether security posture is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose security posture through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of security posture so the requirement is not dead form data.",
  },
  {
    key: "trustBoundaryModel",
    label: "Trust boundary model",
    category: "security",
    impact: "direct",
    outputAreas: ["zone model", "boundary overlays", "policy consequences"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Determines which trust zones must remain separated.",
    validationConsequence: "Design-core traceability must show whether trust boundary model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose trust boundary model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of trust boundary model so the requirement is not dead form data.",
  },
  {
    key: "adminBoundary",
    label: "Administrative boundary",
    category: "security",
    impact: "direct",
    outputAreas: ["privileged admin path", "management isolation", "access review"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Determines administrative separation and privileged access posture.",
    validationConsequence: "Design-core traceability must show whether administrative boundary is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose administrative boundary through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of administrative boundary so the requirement is not dead form data.",
  },
  {
    key: "identityModel",
    label: "Identity model",
    category: "security",
    impact: "indirect",
    outputAreas: ["remote access policy", "admin access", "cloud identity"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Informs access control, VPN, and cloud/admin identity assumptions.",
    validationConsequence: "Design-core traceability must show whether identity model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose identity model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of identity model so the requirement is not dead form data.",
  },
  {
    key: "cloudIdentityBoundary",
    label: "Cloud identity boundary",
    category: "cloud",
    impact: "direct",
    outputAreas: ["hybrid identity", "cloud admin boundary", "policy review"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines identity separation between on-prem and cloud.",
    validationConsequence: "Design-core traceability must show whether cloud identity boundary is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud identity boundary through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud identity boundary so the requirement is not dead form data.",
  },
  {
    key: "cloudTrafficBoundary",
    label: "Cloud traffic boundary",
    category: "cloud",
    impact: "direct",
    outputAreas: ["cloud security boundary", "ingress/egress flows", "hybrid policy"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines public/private cloud traffic separation.",
    validationConsequence: "Design-core traceability must show whether cloud traffic boundary is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud traffic boundary through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud traffic boundary so the requirement is not dead form data.",
  },
  {
    key: "cloudHostingModel",
    label: "Cloud hosting model",
    category: "cloud",
    impact: "direct",
    outputAreas: ["service placement", "cloud workloads", "hybrid topology"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines whether services remain local, split, or cloud-hosted.",
    validationConsequence: "Design-core traceability must show whether cloud hosting model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud hosting model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud hosting model so the requirement is not dead form data.",
  },
  {
    key: "cloudNetworkModel",
    label: "Cloud network model",
    category: "cloud",
    impact: "direct",
    outputAreas: ["cloud subnet model", "hub/spoke cloud", "cloud segmentation"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines VNet/VPC and cloud segmentation expectations.",
    validationConsequence: "Design-core traceability must show whether cloud network model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud network model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud network model so the requirement is not dead form data.",
  },
  {
    key: "cloudRoutingModel",
    label: "Cloud routing model",
    category: "cloud",
    impact: "direct",
    outputAreas: ["route advertisements", "cloud prefixes", "summarization"],
    materializationTargets: ["Cloud edge segment", "Hybrid routing notes", "WAN/cloud diagram"],
    designConsequence: "Determines hybrid route exchange and summarization expectations.",
    validationConsequence: "Design-core traceability must show whether cloud routing model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose cloud routing model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of cloud routing model so the requirement is not dead form data.",
  },
  {
    key: "addressHierarchyModel",
    label: "Address hierarchy model",
    category: "addressing",
    impact: "direct",
    outputAreas: ["org block", "site blocks", "segment subnets"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Defines organization\u2192site\u2192VLAN allocation hierarchy.",
    validationConsequence: "Design-core traceability must show whether address hierarchy model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose address hierarchy model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of address hierarchy model so the requirement is not dead form data.",
  },
  {
    key: "siteBlockStrategy",
    label: "Site block strategy",
    category: "addressing",
    impact: "direct",
    outputAreas: ["site summaries", "route summarization", "reserved capacity"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Determines site block reservation and summarization intent.",
    validationConsequence: "Design-core traceability must show whether site block strategy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose site block strategy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of site block strategy so the requirement is not dead form data.",
  },
  {
    key: "gatewayConvention",
    label: "Gateway convention",
    category: "addressing",
    impact: "direct",
    outputAreas: ["gateway IP", "SVI/interface plan", "validation"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Determines gateway placement convention.",
    validationConsequence: "Design-core traceability must show whether gateway convention is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose gateway convention through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of gateway convention so the requirement is not dead form data.",
  },
  {
    key: "growthBufferModel",
    label: "Growth buffer model",
    category: "addressing",
    impact: "direct",
    outputAreas: ["subnet sizing", "capacity headroom", "future reservations"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Controls capacity headroom expectations.",
    validationConsequence: "Design-core traceability must show whether growth buffer model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose growth buffer model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of growth buffer model so the requirement is not dead form data.",
  },
  {
    key: "reservedRangePolicy",
    label: "Reserved range policy",
    category: "addressing",
    impact: "direct",
    outputAreas: ["infrastructure reserve", "DHCP exclusions", "management ranges"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Determines infrastructure/reserved address expectations.",
    validationConsequence: "Design-core traceability must show whether reserved range policy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose reserved range policy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of reserved range policy so the requirement is not dead form data.",
  },
  {
    key: "managementIpPolicy",
    label: "Management IP policy",
    category: "addressing",
    impact: "direct",
    outputAreas: ["management subnet", "device management IPs", "admin zone"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Determines management address placement.",
    validationConsequence: "Design-core traceability must show whether management ip policy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose management ip policy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of management ip policy so the requirement is not dead form data.",
  },
  {
    key: "siteIdentityCapture",
    label: "Site identity capture",
    category: "naming",
    impact: "indirect",
    outputAreas: ["site records", "site labels", "handoff fields"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Determines site identity evidence needed for useful handoff.",
    validationConsequence: "Design-core traceability must show whether site identity capture is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose site identity capture through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of site identity capture so the requirement is not dead form data.",
  },
  {
    key: "namingStandard",
    label: "Naming standard",
    category: "naming",
    impact: "indirect",
    outputAreas: ["device names", "site labels", "report consistency"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Defines naming style for generated/reviewed objects.",
    validationConsequence: "Design-core traceability must show whether naming standard is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose naming standard through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of naming standard so the requirement is not dead form data.",
  },
  {
    key: "deviceNamingConvention",
    label: "Device naming convention",
    category: "naming",
    impact: "indirect",
    outputAreas: ["device names", "diagram labels", "implementation templates"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Determines generated network device naming style.",
    validationConsequence: "Design-core traceability must show whether device naming convention is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose device naming convention through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of device naming convention so the requirement is not dead form data.",
  },
  {
    key: "namingTokenPreference",
    label: "Naming token preference",
    category: "naming",
    impact: "indirect",
    outputAreas: ["site codes", "labels", "object IDs"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Determines which tokens are preferred in object names.",
    validationConsequence: "Design-core traceability must show whether naming token preference is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose naming token preference through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of naming token preference so the requirement is not dead form data.",
  },
  {
    key: "namingHierarchy",
    label: "Naming hierarchy",
    category: "naming",
    impact: "indirect",
    outputAreas: ["building/floor/role labels", "device identity", "handoff structure"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Determines hierarchical naming evidence.",
    validationConsequence: "Design-core traceability must show whether naming hierarchy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose naming hierarchy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of naming hierarchy so the requirement is not dead form data.",
  },
  {
    key: "customNamingPattern",
    label: "Custom naming pattern",
    category: "naming",
    impact: "indirect",
    outputAreas: ["custom labels", "handoff review", "implementation templates"],
    materializationTargets: ["Site/device labels", "Report consistency", "Implementation template names"],
    designConsequence: "Captures custom naming pattern for engineer review.",
    validationConsequence: "Design-core traceability must show whether custom naming pattern is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose custom naming pattern through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of custom naming pattern so the requirement is not dead form data.",
  },
  {
    key: "monitoringModel",
    label: "Monitoring model",
    category: "operations",
    impact: "direct",
    outputAreas: ["operations segment", "monitoring flows", "handoff checks"],
    materializationTargets: ["Operations segment", "Monitoring/logging flows", "Handoff tasks"],
    designConsequence: "Creates/strengthens operations/monitoring design expectations.",
    validationConsequence: "Design-core traceability must show whether monitoring model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose monitoring model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of monitoring model so the requirement is not dead form data.",
  },
  {
    key: "loggingModel",
    label: "Logging model",
    category: "operations",
    impact: "direct",
    outputAreas: ["operations segment", "syslog flows", "compliance evidence"],
    materializationTargets: ["Operations segment", "Monitoring/logging flows", "Handoff tasks"],
    designConsequence: "Creates/strengthens logging/event-retention expectations.",
    validationConsequence: "Design-core traceability must show whether logging model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose logging model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of logging model so the requirement is not dead form data.",
  },
  {
    key: "backupPolicy",
    label: "Backup policy",
    category: "operations",
    impact: "direct",
    outputAreas: ["operations segment", "config backup checks", "handoff tasks"],
    materializationTargets: ["Operations segment", "Monitoring/logging flows", "Handoff tasks"],
    designConsequence: "Creates/strengthens backup/restore operational expectations.",
    validationConsequence: "Design-core traceability must show whether backup policy is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose backup policy through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of backup policy so the requirement is not dead form data.",
  },
  {
    key: "operationsOwnerModel",
    label: "Operations owner model",
    category: "operations",
    impact: "indirect",
    outputAreas: ["handoff ownership", "support model", "review notes"],
    materializationTargets: ["Operations segment", "Monitoring/logging flows", "Handoff tasks"],
    designConsequence: "Determines who owns operating the design after delivery.",
    validationConsequence: "Design-core traceability must show whether operations owner model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose operations owner model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of operations owner model so the requirement is not dead form data.",
  },
  {
    key: "siteLayoutModel",
    label: "Site layout model",
    category: "physical",
    impact: "indirect",
    outputAreas: ["site placement", "access edge", "diagram grouping"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Determines physical site layout assumptions.",
    validationConsequence: "Design-core traceability must show whether site layout model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose site layout model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of site layout model so the requirement is not dead form data.",
  },
  {
    key: "physicalScope",
    label: "Physical scope",
    category: "physical",
    impact: "indirect",
    outputAreas: ["closet detail", "diagram detail", "handoff limits"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Determines how detailed physical placement should be.",
    validationConsequence: "Design-core traceability must show whether physical scope is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose physical scope through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of physical scope so the requirement is not dead form data.",
  },
  {
    key: "printerCount",
    label: "Printer count",
    category: "edge",
    impact: "direct",
    outputAreas: ["printer host demand", "printer VLAN sizing", "DHCP planning"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Sizes printer/shared-device segment.",
    validationConsequence: "Design-core traceability must show whether printer count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose printer count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of printer count so the requirement is not dead form data.",
  },
  {
    key: "phoneCount",
    label: "Phone count",
    category: "edge",
    impact: "direct",
    outputAreas: ["voice host demand", "voice VLAN sizing", "QoS review"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Sizes voice segment.",
    validationConsequence: "Design-core traceability must show whether phone count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose phone count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of phone count so the requirement is not dead form data.",
  },
  {
    key: "apCount",
    label: "AP count",
    category: "edge",
    impact: "direct",
    outputAreas: ["AP management demand", "staff Wi-Fi sizing", "PoE/access review"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Sizes wireless/AP expectations.",
    validationConsequence: "Design-core traceability must show whether ap count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose ap count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of ap count so the requirement is not dead form data.",
  },
  {
    key: "cameraCount",
    label: "Camera count",
    category: "security",
    impact: "direct",
    outputAreas: ["camera host demand", "camera VLAN sizing", "security-device policy"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Sizes camera/security-device segment.",
    validationConsequence: "Design-core traceability must show whether camera count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose camera count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of camera count so the requirement is not dead form data.",
  },
  {
    key: "serverCount",
    label: "Server count",
    category: "services",
    impact: "direct",
    outputAreas: ["server host demand", "services VLAN sizing", "service placement"],
    materializationTargets: ["Services segment", "Service placement", "Traffic flows"],
    designConsequence: "Sizes services/server segment.",
    validationConsequence: "Design-core traceability must show whether server count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose server count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of server count so the requirement is not dead form data.",
  },
  {
    key: "iotDeviceCount",
    label: "IoT device count",
    category: "security",
    impact: "direct",
    outputAreas: ["IoT host demand", "IoT VLAN sizing", "specialty-device policy"],
    materializationTargets: ["Security zones", "Policy consequences", "Validation blockers", "Diagram boundaries"],
    designConsequence: "Sizes IoT/specialty-device segment.",
    validationConsequence: "Design-core traceability must show whether iot device count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose iot device count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of iot device count so the requirement is not dead form data.",
  },
  {
    key: "wiredWirelessMix",
    label: "Wired/wireless mix",
    category: "edge",
    impact: "direct",
    outputAreas: ["user demand split", "access edge", "wireless sizing"],
    materializationTargets: ["VLAN/segment rows", "Access edge notes", "Diagram placement"],
    designConsequence: "Adjusts user/wireless assumptions and access-edge notes.",
    validationConsequence: "Design-core traceability must show whether wired/wireless mix is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose wired/wireless mix through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of wired/wireless mix so the requirement is not dead form data.",
  },
  {
    key: "siteRoleModel",
    label: "Site role model",
    category: "physical",
    impact: "indirect",
    outputAreas: ["HQ/branch role", "topology labels", "WAN assumptions"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Determines how sites are labelled and reviewed.",
    validationConsequence: "Design-core traceability must show whether site role model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose site role model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of site role model so the requirement is not dead form data.",
  },
  {
    key: "buildingCount",
    label: "Building count",
    category: "physical",
    impact: "indirect",
    outputAreas: ["physical topology", "closet count review", "access edge"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Controls physical/site detail assumptions.",
    validationConsequence: "Design-core traceability must show whether building count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose building count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of building count so the requirement is not dead form data.",
  },
  {
    key: "floorCount",
    label: "Floor count",
    category: "physical",
    impact: "indirect",
    outputAreas: ["access distribution", "closet review", "wireless density"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Controls floor/closet/access review.",
    validationConsequence: "Design-core traceability must show whether floor count is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose floor count through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of floor count so the requirement is not dead form data.",
  },
  {
    key: "closetModel",
    label: "Closet model",
    category: "physical",
    impact: "indirect",
    outputAreas: ["access switch placement", "MDF/IDF review", "diagram grouping"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Controls access closet topology assumptions.",
    validationConsequence: "Design-core traceability must show whether closet model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose closet model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of closet model so the requirement is not dead form data.",
  },
  {
    key: "edgeFootprint",
    label: "Edge footprint",
    category: "physical",
    impact: "indirect",
    outputAreas: ["edge device count", "access topology", "site constraints"],
    materializationTargets: ["Site records", "Physical topology labels", "Diagram placement"],
    designConsequence: "Controls compact vs expanded edge placement assumptions.",
    validationConsequence: "Design-core traceability must show whether edge footprint is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose edge footprint through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of edge footprint so the requirement is not dead form data.",
  },
  {
    key: "applicationProfile",
    label: "Application profile",
    category: "services",
    impact: "indirect",
    outputAreas: ["traffic profile", "service placement", "security flows"],
    materializationTargets: ["Services segment", "Service placement", "Traffic flows"],
    designConsequence: "Informs expected application traffic and service dependencies.",
    validationConsequence: "Design-core traceability must show whether application profile is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose application profile through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of application profile so the requirement is not dead form data.",
  },
  {
    key: "criticalServicesModel",
    label: "Critical services model",
    category: "services",
    impact: "direct",
    outputAreas: ["services segment", "operations flows", "resilience review"],
    materializationTargets: ["Services segment", "Service placement", "Traffic flows"],
    designConsequence: "Determines which services require explicit placement/review.",
    validationConsequence: "Design-core traceability must show whether critical services model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose critical services model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of critical services model so the requirement is not dead form data.",
  },
  {
    key: "interSiteTrafficModel",
    label: "Inter-site traffic model",
    category: "wan",
    impact: "direct",
    outputAreas: ["WAN capacity", "route intent", "traffic flows"],
    materializationTargets: ["WAN/transit segment", "Routing intent", "Flow review"],
    designConsequence: "Determines WAN traffic emphasis and centralization risk.",
    validationConsequence: "Design-core traceability must show whether inter-site traffic model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose inter-site traffic model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of inter-site traffic model so the requirement is not dead form data.",
  },
  {
    key: "bandwidthProfile",
    label: "Bandwidth profile",
    category: "wan",
    impact: "indirect",
    outputAreas: ["WAN sizing notes", "performance review", "QoS assumptions"],
    materializationTargets: ["WAN/transit segment", "Routing intent", "Flow review"],
    designConsequence: "Informs bandwidth/performance expectations.",
    validationConsequence: "Design-core traceability must show whether bandwidth profile is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose bandwidth profile through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of bandwidth profile so the requirement is not dead form data.",
  },
  {
    key: "latencySensitivity",
    label: "Latency sensitivity",
    category: "wan",
    impact: "indirect",
    outputAreas: ["QoS review", "WAN path quality", "app performance"],
    materializationTargets: ["WAN/transit segment", "Routing intent", "Flow review"],
    designConsequence: "Informs latency-sensitive design assumptions.",
    validationConsequence: "Design-core traceability must show whether latency sensitivity is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose latency sensitivity through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of latency sensitivity so the requirement is not dead form data.",
  },
  {
    key: "qosModel",
    label: "QoS model",
    category: "wan",
    impact: "direct",
    outputAreas: ["QoS plan", "voice/app prioritization", "validation review"],
    materializationTargets: ["WAN/transit segment", "Routing intent", "Flow review"],
    designConsequence: "Determines traffic prioritization expectations.",
    validationConsequence: "Design-core traceability must show whether qos model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose qos model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of qos model so the requirement is not dead form data.",
  },
  {
    key: "outageTolerance",
    label: "Outage tolerance",
    category: "resilience",
    impact: "direct",
    outputAreas: ["resilience posture", "change risk", "HA review"],
    materializationTargets: ["Redundancy review", "WAN/edge posture", "Implementation risk"],
    designConsequence: "Determines acceptable outage/risk posture.",
    validationConsequence: "Design-core traceability must show whether outage tolerance is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose outage tolerance through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of outage tolerance so the requirement is not dead form data.",
  },
  {
    key: "growthHorizon",
    label: "Growth horizon",
    category: "addressing",
    impact: "direct",
    outputAreas: ["capacity reserve", "future site/segment headroom", "report assumptions"],
    materializationTargets: ["CIDR allocation notes", "Gateway convention", "Capacity review"],
    designConsequence: "Determines planning horizon and growth headroom.",
    validationConsequence: "Design-core traceability must show whether growth horizon is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose growth horizon through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of growth horizon so the requirement is not dead form data.",
  },
  {
    key: "budgetModel",
    label: "Budget model",
    category: "constraints",
    impact: "indirect",
    outputAreas: ["tradeoffs", "redundancy assumptions", "risk notes"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Constrains design ambition and report tradeoffs.",
    validationConsequence: "Design-core traceability must show whether budget model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose budget model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of budget model so the requirement is not dead form data.",
  },
  {
    key: "vendorPreference",
    label: "Vendor preference",
    category: "constraints",
    impact: "indirect",
    outputAreas: ["implementation templates", "support model", "handoff notes"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Keeps output vendor-neutral or vendor-aware.",
    validationConsequence: "Design-core traceability must show whether vendor preference is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose vendor preference through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of vendor preference so the requirement is not dead form data.",
  },
  {
    key: "implementationTimeline",
    label: "Implementation timeline",
    category: "constraints",
    impact: "indirect",
    outputAreas: ["rollout sequencing", "implementation risk", "handoff plan"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Informs rollout planning and task sequencing.",
    validationConsequence: "Design-core traceability must show whether implementation timeline is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose implementation timeline through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of implementation timeline so the requirement is not dead form data.",
  },
  {
    key: "rolloutModel",
    label: "Rollout model",
    category: "constraints",
    impact: "indirect",
    outputAreas: ["cutover plan", "validation gates", "migration phases"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Informs phased/parallel/big-bang rollout posture.",
    validationConsequence: "Design-core traceability must show whether rollout model is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose rollout model through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of rollout model so the requirement is not dead form data.",
  },
  {
    key: "downtimeConstraint",
    label: "Downtime constraint",
    category: "constraints",
    impact: "direct",
    outputAreas: ["change windows", "rollback requirements", "implementation blockers"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Controls outage-sensitive implementation review.",
    validationConsequence: "Design-core traceability must show whether downtime constraint is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose downtime constraint through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of downtime constraint so the requirement is not dead form data.",
  },
  {
    key: "teamCapability",
    label: "Team capability",
    category: "constraints",
    impact: "indirect",
    outputAreas: ["handoff depth", "supportability", "complexity tradeoffs"],
    materializationTargets: ["Implementation plan", "Risk review", "Report tradeoffs"],
    designConsequence: "Controls complexity and supportability notes.",
    validationConsequence: "Design-core traceability must show whether team capability is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose team capability through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of team capability so the requirement is not dead form data.",
  },
  {
    key: "outputPackage",
    label: "Output package",
    category: "handoff",
    impact: "direct",
    outputAreas: ["report depth", "exports", "stakeholder summary"],
    materializationTargets: ["Report/export evidence", "Traceability table", "Review notes"],
    designConsequence: "Determines report/export shape and evidence level.",
    validationConsequence: "Design-core traceability must show whether output package is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose output package through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of output package so the requirement is not dead form data.",
  },
  {
    key: "primaryAudience",
    label: "Primary audience",
    category: "handoff",
    impact: "direct",
    outputAreas: ["report tone", "technical detail", "stakeholder summary"],
    materializationTargets: ["Report/export evidence", "Traceability table", "Review notes"],
    designConsequence: "Determines who the outputs must satisfy.",
    validationConsequence: "Design-core traceability must show whether primary audience is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose primary audience through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of primary audience so the requirement is not dead form data.",
  },
  {
    key: "customRequirementsNotes",
    label: "Custom notes",
    category: "handoff",
    impact: "indirect",
    outputAreas: ["review notes", "manual assumptions", "report appendix"],
    materializationTargets: ["Report/export evidence", "Traceability table", "Review notes"],
    designConsequence: "Preserves user-specific requirements for review.",
    validationConsequence: "Design-core traceability must show whether custom notes is reflected in concrete outputs or only review notes.",
    diagramConsequence: "Diagram evidence should expose custom notes through placement, labels, overlays, or an explicit not-applicable status.",
    reportConsequence: "Report evidence must explain the consequence of custom notes so the requirement is not dead form data.",
  },
];

export const REQUIREMENT_FIELD_KEYS = REQUIREMENT_IMPACT_REGISTRY.map((item) => item.key);

export function requirementValueToString(value: unknown): string {
  if (typeof value === "boolean") return value ? "selected" : "not selected";
  if (typeof value === "number") return Number.isFinite(value) ? String(value) : "";
  if (typeof value === "string") return value.trim();
  if (Array.isArray(value)) return value.map((item) => requirementValueToString(item)).filter(Boolean).join(", ");
  return "";
}

export function buildRequirementImpactInventory(requirements: Record<string, unknown>): RequirementImpactInventoryRow[] {
  return REQUIREMENT_IMPACT_REGISTRY.map((item) => {
    const sourceValue = requirementValueToString(requirements[item.key]);
    return {
      ...item,
      sourceValue: sourceValue || "not captured",
      captured: Boolean(sourceValue),
    };
  });
}

export function summarizeRequirementImpactInventory(requirements: Record<string, unknown>) {
  const rows = buildRequirementImpactInventory(requirements);
  return {
    totalFieldCount: rows.length,
    capturedFieldCount: rows.filter((row) => row.captured).length,
    directFieldCount: rows.filter((row) => row.impact === "direct").length,
    indirectFieldCount: rows.filter((row) => row.impact === "indirect").length,
    evidenceFieldCount: rows.filter((row) => row.impact === "evidence").length,
    categories: Array.from(new Set(rows.map((row) => row.category))).sort(),
  };
}
