import assert from "node:assert/strict";
import { buildV1DesignGraphControl } from "../services/designCore/designCore.designGraphControl.js";
import type { BackendDiagramTruthModel, NetworkObjectModel, V1RequirementsClosureControlSummary, V1NetworkObjectLineageRow, V1NetworkObjectModelControlSummary } from "../services/designCore.types.js";

const baseImpact = { validationImpact: "READY: graph dependency is covered by validation readiness.", frontendDisplayImpact: ["ProjectOverviewPage.V1DesignGraph"], reportExportImpact: ["V1 Design Graph Dependency Integrity"], diagramImpact: ["diagramTruth.renderModel"] };
const objectLineage: V1NetworkObjectLineageRow[] = [
  { objectId: "zone-guest", objectType: "security-zone", objectRole: "guest", truthState: "proposed", sourceType: "REQUIREMENT_MATERIALIZED", sourceRequirementIds: ["req-guestWifi"], sourceObjectIds: ["requirements:guestWifi"], sourceEngine: "designCore.networkObjectModel.V1", confidence: "medium", proofStatus: "PARTIAL", implementationReadiness: "DRAFT_ONLY", displayName: "Guest Zone", relatedObjectIds: ["10.10.20.0/24"], hasCompleteMetadata: true, missingMetadataFields: [], ...baseImpact },
  { objectId: "policy-guest-deny", objectType: "policy-rule", objectRole: "deny", truthState: "proposed", sourceType: "REQUIREMENT_MATERIALIZED", sourceRequirementIds: ["req-guestWifi"], sourceObjectIds: ["zone-guest", "zone-internal"], sourceEngine: "designCore.networkObjectModel.V1", confidence: "medium", proofStatus: "PARTIAL", implementationReadiness: "DRAFT_ONLY", displayName: "Deny Guest Internal", relatedObjectIds: ["zone-guest", "zone-internal"], hasCompleteMetadata: true, missingMetadataFields: [], ...baseImpact },
];
const graph = { summary: { nodeCount: 4, edgeCount: 3, requiredEdgeCount: 3, connectedObjectCount: 4, orphanObjectCount: 0, integrityFindingCount: 0, blockingFindingCount: 0, relationshipCoveragePercent: 100, notes: [] }, nodes: [ { id: "graph-node-zone-guest", objectType: "security-zone" as const, objectId: "zone-guest", label: "Guest Zone", truthState: "proposed" as const, notes: [] }, { id: "graph-node-policy-guest-deny", objectType: "policy-rule" as const, objectId: "policy-guest-deny", label: "Deny Guest Internal", truthState: "proposed" as const, notes: [] }, { id: "graph-node-flow-guest-internal", objectType: "security-flow" as const, objectId: "flow-guest-internal", label: "Guest to Internal blocked", truthState: "proposed" as const, notes: [] }, { id: "graph-node-subnet-guest", objectType: "subnet" as const, objectId: "10.10.20.0/24", label: "10.10.20.0/24", truthState: "proposed" as const, notes: [] } ], edges: [ { id: "edge-zone-subnet", relationship: "security-zone-protects-subnet" as const, sourceNodeId: "graph-node-zone-guest", targetNodeId: "graph-node-subnet-guest", truthState: "proposed" as const, required: true, notes: [] }, { id: "edge-zone-flow", relationship: "security-zone-initiates-security-flow" as const, sourceNodeId: "graph-node-zone-guest", targetNodeId: "graph-node-flow-guest-internal", truthState: "proposed" as const, required: true, notes: [] }, { id: "edge-flow-policy", relationship: "security-flow-covered-by-policy" as const, sourceNodeId: "graph-node-flow-guest-internal", targetNodeId: "graph-node-policy-guest-deny", truthState: "proposed" as const, required: true, notes: [] } ], integrityFindings: [] };
const networkObjectModel = { summary: {}, routeDomains: [], securityZones: [{ id: "zone-guest", name: "Guest", zoneRole: "guest", truthState: "proposed", siteIds: ["site-1"], vlanIds: [20], subnetCidrs: ["10.10.20.0/24"], routeDomainId: "rd-1", isolationExpectation: "isolated", notes: [] }], devices: [], interfaces: [], links: [], policyRules: [{ id: "policy-guest-deny", name: "Deny Guest Internal", sourceZoneId: "zone-guest", destinationZoneId: "zone-internal", action: "deny", services: ["any"], truthState: "proposed", rationale: "Guest isolation", notes: [] }], natRules: [], dhcpPools: [], ipReservations: [], designGraph: graph, routingSegmentation: { summary: {}, routeDomains: [], routeIntents: [], routeTableEntries: [], segmentationMatrix: [], reachabilityFindings: [] }, securityPolicyFlow: { summary: {}, serviceObjects: [], flowRequirements: [], policyMatrix: [], natReviews: [], loggingReviews: [], policyFindings: [] }, implementationPlan: { summary: {}, stages: [], steps: [], verificationChecks: [], rollbackActions: [], findings: [] }, integrityNotes: [] } as unknown as NetworkObjectModel;
const V1 = { contract: "V1_NETWORK_OBJECT_MODEL_TRUTH_CONTRACT", role: "TRUTH_LABELLED_NETWORK_OBJECT_MODEL_NOT_FAKE_TOPOLOGY", overallReadiness: "READY", objectCount: 2, metadataCompleteObjectCount: 2, metadataGapObjectCount: 0, fakeAuthorityRiskCount: 0, requirementLineageRowCount: 1, requirementLineageGapCount: 0, implementationReadyObjectCount: 0, implementationReviewObjectCount: 2, implementationBlockedObjectCount: 0, objectLineage, requirementObjectLineage: [{ requirementId: "req-guestWifi", sourceKey: "guestWifi", lifecycleStatus: "FULLY_PROPAGATED", expectedObjectTypes: ["security-zone", "policy-rule"], actualObjectIds: ["zone-guest", "policy-guest-deny"], actualObjectTypes: ["security-zone", "policy-rule"], missingObjectTypes: [], readinessImpact: "READY", notes: [] }], findings: [], notes: [] } as unknown as V1NetworkObjectModelControlSummary;
const V1 = { closureMatrix: [{ requirementId: "req-guestWifi", key: "guestWifi", lifecycleStatus: "FULLY_PROPAGATED" }] } as unknown as V1RequirementsClosureControlSummary;
const diagramTruth = { renderModel: { nodes: [{ objectId: "zone-guest" }, { objectId: "policy-guest-deny" }] } } as unknown as BackendDiagramTruthModel;
const result = buildV1DesignGraphControl({ networkObjectModel, V1NetworkObjectModel: V1, V1RequirementsClosure: V1, diagramTruth });
assert.equal(result.contract, "V1_DESIGN_GRAPH_DEPENDENCY_INTEGRITY_CONTRACT");
assert.equal(result.role, "REQUIREMENT_TO_OBJECT_TO_CONSUMER_DEPENDENCY_GRAPH");
assert.equal(result.objectCoverageGapCount, 0);
assert.equal(result.requirementPathBlockedCount, 0);
assert.ok(result.requirementDependencyPaths[0]?.actualRelationshipTypes.includes("security-flow-covered-by-policy"));
assert.ok(result.findings.some((finding) => finding.code === "V1_DESIGN_GRAPH_DEPENDENCIES_COMPLETE"));
console.log("[V1] Design graph dependency integrity selftest passed");
