import { Router } from "express";
import { requireAuth } from "../middleware/auth.js";
import * as enterpriseIpamController from "../controllers/enterpriseIpam.controller.js";
import { asyncHandler } from "../utils/asyncHandler.js";

const router = Router();
router.use(requireAuth);
router.get("/projects/:projectId", asyncHandler(enterpriseIpamController.getEnterpriseIpamSnapshot));
router.get("/projects/:projectId/brownfield-conflicts", asyncHandler(enterpriseIpamController.getBrownfieldConflictReview));
router.post("/projects/:projectId/route-domains", asyncHandler(enterpriseIpamController.createRouteDomain));
router.post("/projects/:projectId/ip-pools", asyncHandler(enterpriseIpamController.createIpPool));
router.post("/projects/:projectId/ip-allocations", asyncHandler(enterpriseIpamController.createIpAllocation));
router.post("/projects/:projectId/ip-allocations/from-plan", asyncHandler(enterpriseIpamController.createAllocationFromPlan));
router.post("/projects/:projectId/dhcp-scopes", asyncHandler(enterpriseIpamController.createDhcpScope));
router.post("/projects/:projectId/reservations", asyncHandler(enterpriseIpamController.createIpReservation));
router.post("/projects/:projectId/brownfield-imports/dry-run", asyncHandler(enterpriseIpamController.previewBrownfieldImport));
router.post("/projects/:projectId/brownfield-imports", asyncHandler(enterpriseIpamController.createBrownfieldImport));
router.post("/projects/:projectId/brownfield-conflict-resolutions", asyncHandler(enterpriseIpamController.createBrownfieldConflictResolution));
router.post("/projects/:projectId/allocation-approvals", asyncHandler(enterpriseIpamController.createAllocationApproval));
router.patch("/route-domains/:id", asyncHandler(enterpriseIpamController.updateRouteDomain));
router.delete("/route-domains/:id", asyncHandler(enterpriseIpamController.deleteRouteDomain));
router.patch("/ip-pools/:id", asyncHandler(enterpriseIpamController.updateIpPool));
router.delete("/ip-pools/:id", asyncHandler(enterpriseIpamController.deleteIpPool));
router.patch("/ip-allocations/:id", asyncHandler(enterpriseIpamController.updateIpAllocation));
router.patch("/ip-allocations/:id/status", asyncHandler(enterpriseIpamController.updateIpAllocationStatus));
router.delete("/ip-allocations/:id", asyncHandler(enterpriseIpamController.deleteIpAllocation));
router.patch("/dhcp-scopes/:id", asyncHandler(enterpriseIpamController.updateDhcpScope));
router.delete("/dhcp-scopes/:id", asyncHandler(enterpriseIpamController.deleteDhcpScope));
router.patch("/reservations/:id", asyncHandler(enterpriseIpamController.updateIpReservation));
router.delete("/reservations/:id", asyncHandler(enterpriseIpamController.deleteIpReservation));
router.patch("/brownfield-networks/:id", asyncHandler(enterpriseIpamController.updateBrownfieldNetwork));
router.delete("/brownfield-networks/:id", asyncHandler(enterpriseIpamController.deleteBrownfieldNetwork));
export default router;
